server:
  port: 8080
  tomcat:
    connection-timeout: 60000 # 60秒超时
    max-swallow-size: 100MB   # 允许吞下的最大数据量

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/jienoshiri_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: demaxiya666
  servlet:
    servlet:
      multipart:
        enabled: true
        # 单个文件最大限制（设为100MB，足够应付你的67MB）
        max-file-size: 100MB
        # 单次请求总限制
        max-request-size: 200MB
        # 超过这个大小则写入磁盘临时文件，防止内存溢出
        file-size-threshold: 2KB
  data:
    redis:
      host: localhost
      port: 6379
      password: ""  # パスワードがない場合は空文字、設定している場合は記入
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
  elasticsearch:
    uris: http://localhost:9200
    socket-timeout: 10000ms
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: jienoshiri

